[project]
name = "ws-espy"
version = "2025.10.11"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

[dependency-groups]
dev = [
    "esptool>=5.1.0",
    "micropython-esp32-stubs>=1.26.0.post1",
    "mpremote>=1.26.1",
]
